# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = nordvpn connect
exec-once = ~/.local/bin/voxtype-tray-wait &
exec-once = qs -d
exec-once = theme-cache-missing &
