# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F3F0F0
background         #262626
cursor             #B0AAAB

active_tab_foreground     #262626
active_tab_background     #F3F0F0
inactive_tab_foreground   #F3F0F0
inactive_tab_background   #262626

active_border_color   #F3F0F0
inactive_border_color #262626
bell_border_color     #262426

color0      #4C4B4C
color1		#262426
color2		#524C4C
color3		#504D4E
color4		#726868
color5		#7B7577
color6		#A59E9F
color7		#E5E1E1
color8		#A09D9E
color9		#323033
color10		#6E6565
color11		#6B6668
color12		#988B8A
color13		#A39D9E
color14		#DCD3D4
color15		#E5E1E1
