# Telegram Desktop theme

local TG_THEME="$HOME/.config/theme/telegram.tdesktop-theme"
local msg_out_bg
msg_out_bg=$(python3 -c "
def blend(c1,c2,r):
  return ''.join(f'{int(int(c1[i:i+2],16)*(1-r)+int(c2[i:i+2],16)*r):02x}' for i in (0,2,4))
print(blend('${C[bg]}','${C[blue]}',0.12 if $(${is_light} && echo 1 || echo 0) else 0.15))
")
cat > "$TG_THEME" << TGEOF
// Auto-generated by theme sync — $(date +%F)
// Window
windowBg: #${C[bg]};
windowFg: #${C[fg]};
windowBgOver: #${C[bg_light]};
windowBgRipple: #${C[bg_highlight]};
windowFgOver: #${C[fg]};
windowSubTextFg: #${C[fg_dim]};
windowSubTextFgOver: #${C[fg_dim]};
windowBoldFg: #${C[fg]};
windowBoldFgOver: #${C[fg]};
windowBgActive: #${C[blue]};
windowFgActive: #${C[bg]};
windowActiveTextFg: #${C[blue]};
windowShadowFg: #${C[bg]}00;
windowShadowFgFallback: #${C[bg_highlight]};
// Title bar
titleBg: #${C[bg_light]};
titleBgActive: #${C[bg_light]};
titleButtonBg: #${C[bg_light]}00;
titleButtonFg: #${C[fg_dim]};
titleButtonBgOver: #${C[bg_highlight]};
titleButtonFgOver: #${C[fg]};
titleButtonBgActive: #${C[bg_highlight]};
titleButtonFgActive: #${C[fg]};
titleButtonBgActiveOver: #${C[bg_highlight]};
titleButtonFgActiveOver: #${C[fg]};
titleButtonCloseBg: #${C[bg_light]}00;
titleButtonCloseFg: #${C[fg_dim]};
titleButtonCloseBgOver: #${C[red]};
titleButtonCloseFgOver: #${C[bg]};
titleFg: #${C[fg]};
titleFgActive: #${C[fg]};
// Menu / sidebar
sideBarBg: #${C[bg]};
sideBarBgActive: #${C[bg_light]};
sideBarBgRipple: #${C[bg_highlight]};
sideBarTextFg: #${C[fg_dim]};
sideBarTextFgActive: #${C[blue]};
sideBarIconFg: #${C[fg_dim]};
sideBarIconFgActive: #${C[blue]};
sideBarBadgeBg: #${C[blue]};
sideBarBadgeBgMuted: #${C[fg_muted]};
sideBarBadgeFg: #${C[bg]};
// Top bar
topBarBg: #${C[bg]};
// Filter / search
searchedBarBg: #${C[bg_highlight]};
// Dialogs (chat list)
dialogsBg: #${C[bg]};
dialogsBgOver: #${C[bg_light]};
dialogsBgActive: #${C[bg_highlight]};
dialogsNameFg: #${C[fg]};
dialogsNameFgActive: #${C[fg]};
dialogsTextFg: #${C[fg_dim]};
dialogsTextFgActive: #${C[fg_dim]};
dialogsTextFgService: #${C[blue]};
dialogsTextFgServiceActive: #${C[blue]};
dialogsDraftFg: #${C[red]};
dialogsDraftFgOver: #${C[red]};
dialogsDraftFgActive: #${C[red]};
dialogsDateFg: #${C[fg_muted]};
dialogsDateFgActive: #${C[fg_muted]};
dialogsUnreadBg: #${C[blue]};
dialogsUnreadBgMuted: #${C[fg_muted]};
dialogsUnreadFg: #${C[bg]};
dialogsOnlineBadgeFg: #${C[green]};
// Chat history
historyTextInFg: #${C[fg]};
historyTextOutFg: #${C[fg]};
historyCaptionInFg: #${C[fg]};
historyCaptionOutFg: #${C[fg]};
historyFileNameInFg: #${C[fg]};
historyFileNameOutFg: #${C[fg]};
historyLinkInFg: #${C[blue]};
historyLinkOutFg: #${C[blue]};
// Message bubbles
msgInBg: #${C[bg_light]};
msgInBgSelected: #${C[bg_highlight]};
msgOutBg: #${msg_out_bg};
msgOutBgSelected: #${C[bg_highlight]};
msgInReplyBarColor: #${C[blue]};
msgOutReplyBarColor: #${C[blue]};
msgInReplyBarSelColor: #${C[blue]};
msgOutReplyBarSelColor: #${C[blue]};
msgInDateFg: #${C[fg_muted]};
msgOutDateFg: #${C[fg_muted]};
msgInDateFgSelected: #${C[fg_dim]};
msgOutDateFgSelected: #${C[fg_dim]};
msgInServiceFg: #${C[blue]};
msgInServiceFgSelected: #${C[blue]};
msgOutServiceFg: #${C[blue]};
msgOutServiceFgSelected: #${C[blue]};
msgInMonoFg: #${C[green]};
msgOutMonoFg: #${C[green]};
msgDateImgBg: #${C[bg]}b0;
msgServiceBg: #${C[bg_highlight]}c0;
msgServiceFg: #${C[fg]};
msgShadow: #00000000;
// Compose area
historyComposeAreaBg: #${C[bg]};
historyComposeAreaFg: #${C[fg]};
historyComposeAreaFgService: #${C[fg_dim]};
historyReplyBg: #${C[bg]};
historySendIconFg: #${C[blue]};
historySendIconFgOver: #${C[bright_blue]};
historyPinnedBg: #${C[bg]};
historyToDownBg: #${C[bg]};
historyToDownBgOver: #${C[bg_light]};
historyToDownBgRipple: #${C[bg_highlight]};
historyToDownFg: #${C[fg_dim]};
historyToDownFgOver: #${C[fg]};
historyToDownShadow: #00000000;
// Input field
filterInputInactiveBg: #${C[bg_light]};
filterInputActiveBg: #${C[bg_light]};
inputBorderFg: #${C[border]};
// Buttons
activeButtonBg: #${C[blue]};
activeButtonBgOver: #${C[bright_blue]};
activeButtonBgRipple: #${C[blue]};
activeButtonFg: #${C[bg]};
activeButtonFgOver: #${C[bg]};
activeButtonSecondaryFg: #${C[bg]};
activeButtonSecondaryFgOver: #${C[bg]};
lightButtonBg: #${C[bg]};
lightButtonBgOver: #${C[bg_light]};
lightButtonBgRipple: #${C[bg_highlight]};
lightButtonFg: #${C[blue]};
lightButtonFgOver: #${C[blue]};
outlineButtonBg: #${C[bg]};
outlineButtonBgOver: #${C[bg_light]};
outlineButtonBgRipple: #${C[bg_highlight]};
outlineButtonOutlineFg: #${C[blue]};
attentionButtonFg: #${C[red]};
attentionButtonFgOver: #${C[red]};
attentionButtonBgOver: #${C[bg_light]};
attentionButtonBgRipple: #${C[bg_highlight]};
// Scrollbar
scrollBarBg: #${C[fg_muted]}80;
scrollBarBgOver: #${C[fg_muted]}b0;
scrollBg: #${C[fg_muted]}10;
scrollBgOver: #${C[fg_muted]}20;
// Media player
mediaPlayerBg: #${C[bg]};
// Tooltips / popups
tooltipBg: #${C[bg_light]};
tooltipFg: #${C[fg]};
tooltipBorderFg: #${C[border]};
// Profile
profileBg: #${C[bg]};
profileStatusFgOver: #${C[blue]};
// Menu / popup
menuBg: #${C[bg]};
menuBgOver: #${C[bg_light]};
menuBgRipple: #${C[bg_highlight]};
menuIconFg: #${C[fg_dim]};
menuIconFgOver: #${C[fg]};
menuFgDisabled: #${C[fg_muted]};
menuSeparatorFg: #${C[border]};
// Placeholder
placeholderFg: #${C[fg_muted]};
placeholderFgActive: #${C[fg_dim]};
// Box / modal
boxBg: #${C[bg]};
boxTextFg: #${C[fg]};
boxSearchBg: #${C[bg_light]};
boxTitleFg: #${C[fg]};
boxTitleCloseFg: #${C[fg_dim]};
boxTitleCloseFgOver: #${C[fg]};
// Checkboxes / radios
checkboxFg: #${C[border]};
radioFg: #${C[border]};
// Inline bot
emojiPanBg: #${C[bg]};
emojiPanHeaderFg: #${C[fg_dim]};
stickerPanDeleteBg: #${C[red]}cc;
stickerPanDeleteFg: #${C[bg]};
TGEOF
echo -e "    ${GREEN}telegram${RESET}"
