# Kitty terminal theme

cat > "$HOME/.config/kitty/theme.conf" << EOF
# Auto-generated by theme sync from ~/.config/theme/palette.conf
background #${C[bg]}
foreground #${C[fg]}
cursor #${C[cursor]}
cursor_text_color #${C[bg]}
selection_background #${C[bg_highlight]}
selection_foreground #${C[fg]}
url_color #${C[url]}

active_tab_background #${C[bg_light]}
active_tab_foreground #${C[fg]}
inactive_tab_background #${C[bg]}
inactive_tab_foreground #${C[fg_muted]}

color0 #${C[black]}
color8 #${C[bright_black]}
color1 #${C[red]}
color9 #${C[bright_red]}
color2 #${C[green]}
color10 #${C[bright_green]}
color3 #${C[yellow]}
color11 #${C[bright_yellow]}
color4 #${C[blue]}
color12 #${C[bright_blue]}
color5 #${C[magenta]}
color13 #${C[bright_magenta]}
color6 #${C[cyan]}
color14 #${C[bright_cyan]}
color7 #${C[white]}
color15 #${C[bright_white]}
EOF
echo -e "    ${GREEN}kitty${RESET}"
