# Neovim colorscheme

cat > "$HOME/.config/nvim/lua/plugins/colorscheme.lua" << EOF
-- Auto-generated by theme sync from ~/.config/theme/palette.conf
return {
  {
    "folke/tokyonight.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      style = "night",
      transparent = false,
      terminal_colors = true,
      styles = {
        comments = { italic = false },
        keywords = { italic = false },
        sidebars = "dark",
        floats = "dark",
      },
      on_colors = function(colors)
        colors.bg = "#${C[bg]}"
        colors.bg_dark = "#${C[bg]}"
        colors.bg_float = "#${C[bg]}"
        colors.bg_popup = "#${C[bg]}"
        colors.bg_sidebar = "#${C[bg]}"
        colors.bg_statusline = "#${C[bg_light]}"
        colors.bg_highlight = "#${C[bg_light]}"
        colors.fg = "#${C[fg]}"
        colors.fg_dark = "#${C[fg_dim]}"
        colors.fg_gutter = "#${C[bg_highlight]}"
        colors.border = "#${C[bg_highlight]}"
        colors.comment = "#${C[fg_muted]}"
      end,
      on_highlights = function(hl, c)
        hl.Normal = { bg = "#${C[bg]}", fg = "#${C[fg]}" }
        hl.NormalNC = { bg = "#${C[bg]}", fg = "#${C[fg]}" }
        hl.NormalFloat = { bg = "#${C[bg]}" }
        hl.NormalSB = { bg = "#${C[bg]}" }
        hl.SignColumn = { bg = "#${C[bg]}" }
        hl.LineNr = { fg = "#${C[border]}", bg = "#${C[bg]}" }
        hl.CursorLineNr = { fg = "#${C[fg_dim]}", bg = "#${C[bg]}" }
        hl.CursorLine = { bg = "#${C[bg_light]}" }
        hl.Visual = { bg = "#${C[bg_highlight]}" }
        hl.Pmenu = { bg = "#${C[bg]}", fg = "#${C[fg]}" }
        hl.PmenuSel = { bg = "#${C[bg_highlight]}", fg = "#ffffff" }
        hl.NeoTreeNormal = { bg = "#${C[bg]}" }
        hl.NeoTreeNormalNC = { bg = "#${C[bg]}" }
        hl.NeoTreeEndOfBuffer = { bg = "#${C[bg]}" }
        hl.TelescopeNormal = { bg = "#${C[bg]}" }
        hl.TelescopeBorder = { bg = "#${C[bg]}", fg = "#${C[bg_highlight]}" }
        hl.StatusLine = { bg = "#${C[bg_light]}", fg = "#${C[fg]}" }
        hl.StatusLineNC = { bg = "#${C[bg]}", fg = "#${C[fg_muted]}" }
        hl.EndOfBuffer = { fg = "#${C[bg]}" }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "tokyonight",
    },
  },
}
EOF
echo -e "    ${GREEN}neovim${RESET}"
