# Waybar status bar

cat > "$HOME/.config/waybar/style-minimal.css" << EOF
/* Auto-generated by theme sync from ~/.config/theme/palette.conf */
/* Monochrome Minimal Waybar - R7 Style */

* {
  font-family: "${FONT}", "NotoSans Nerd Font", sans-serif;
  font-size: 13px;
  font-weight: 500;
  min-height: 0;
  padding: 0;
}

#waybar {
  background: transparent;
  color: #${C[fg]};
  margin: 0;
  font-weight: 500;
}

/* --- All modules base style --- */
#workspaces,
#clock,
#tray,
#bluetooth,
#network,
#pulseaudio,
#backlight,
#battery,
#custom-power {
  background-color: #${C[bg]};
  padding: 0.25rem 0.6rem;
  margin: 3px 2px;
  border-radius: 4px;
  box-shadow: 0 1px 4px ${shadow};
  transition: background-color 0.2s ease-in-out;
}

/* --- Workspaces --- */
#workspaces {
  padding: 0.15rem 0.3rem;
}

#workspaces button {
  color: #${C[fg_muted]};
  border-radius: 3px;
  padding: 0.2rem 0.4rem;
  margin: 0 1px;
  background: transparent;
  border: none;
  transition: all 0.2s ease-in-out;
}

#workspaces button.active {
  color: #${C[bg]};
  background-color: #${accent};
}

#workspaces button:hover {
  background: #${C[bg_light]};
  color: #${C[fg]};
}

/* --- Clock --- */
#clock {
  color: #${accent};
  font-weight: 600;
}

/* --- Right modules seamless bar --- */
#tray,
#bluetooth,
#network,
#pulseaudio,
#backlight,
#battery {
  border-radius: 0;
  margin: 3px 0;
  box-shadow: none;
}

#tray {
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
  margin-left: 2px;
}

#battery {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px;
}

/* --- Focus Mode indicator --- */
#custom-focus {
  background-color: #${C[bg_light]};
  padding: 0.25rem 0.6rem 0.25rem 0.4rem;
  margin: 3px 2px;
  margin-right: 6px;
  border-radius: 4px;
  color: #${accent};
  font-size: 14px;
  box-shadow: 0 1px 4px ${shadow};
}

#custom-focus:hover {
  background-color: #${C[border]};
}

/* --- Language indicator --- */
#language {
  background-color: #${C[bg]};
  padding: 0.25rem 0.6rem;
  margin: 3px 2px;
  margin-right: 6px;
  border-radius: 4px;
  border: 1px solid #${C[border]};
  color: #${C[fg_dim]};
  font-weight: 600;
  box-shadow: 0 1px 4px ${shadow};
}

#language:hover {
  background-color: #${C[bg_light]};
  color: #${accent};
}

/* --- Power button separate --- */
#custom-power {
  margin-left: 3px;
  margin-right: 4px;
  color: #${C[fg_muted]};
}

#custom-power:hover {
  background-color: #${C[bg_light]};
  color: #${C[red]};
}

/* --- Hover effects --- */
#workspaces:hover,
#clock:hover,
#tray:hover,
#bluetooth:hover,
#network:hover,
#pulseaudio:hover,
#backlight:hover,
#battery:hover {
  background-color: #${C[bg_light]};
}

/* --- Module colors --- */
#bluetooth {
  color: #${C[fg_muted]};
  font-size: 15px;
}

#bluetooth.connected {
  color: #${accent};
}

#network {
  color: #${C[fg_dim]};
}

#network.disconnected {
  color: #${C[red]};
}

#pulseaudio {
  color: #${C[fg]};
}

#pulseaudio.muted {
  color: #${C[fg_muted]};
}

#backlight {
  color: #${C[fg_dim]};
}

#battery {
  color: #${C[fg]};
}

#battery.charging {
  color: #${C[fg_dim]};
}

#battery.warning:not(.charging) {
  color: #${C[red]};
}

#battery.critical:not(.charging) {
  color: #${C[red]};
  animation: blink 0.5s steps(12) infinite alternate;
}

@keyframes blink {
  to { color: #${C[fg_muted]}; }
}

/* --- Tooltip --- */
tooltip {
  background-color: #${C[bg]};
  color: #${C[fg]};
  padding: 8px 14px;
  border-radius: 8px;
  border: 1px solid #${C[border]};
  box-shadow: 0 4px 12px ${shadow};
}

tooltip label {
  color: #${C[fg]};
}
EOF
echo -e "    ${GREEN}waybar${RESET}"
