# Zen Browser userChrome.css theme sync

local ZEN_PROFILE
ZEN_PROFILE=$(find "$HOME/.zen" -maxdepth 1 -name "*.Default*release*" -type d | head -1)
[[ -z "$ZEN_PROFILE" ]] && return

local CHROME_DIR="$ZEN_PROFILE/chrome"
mkdir -p "$CHROME_DIR"

cat > "$CHROME_DIR/userChrome-theme.css" << EOF
/* Auto-generated by theme sync */
:root {
  --zen-primary-color: #${C[accent]:-${C[blue]}} !important;
  --zen-colors-primary: #${C[accent]:-${C[blue]}} !important;
  --zen-colors-secondary: #${C[accent_secondary]:-${C[magenta]}} !important;
  --zen-colors-tertiary: #${C[accent_tertiary]:-${C[green]}} !important;
  --toolbar-bgcolor: #${C[bg]} !important;
  --toolbar-color: #${C[fg]} !important;
  --urlbar-background-color: #${C[bg_light]} !important;
  --tab-selected-bgcolor: #${C[bg_highlight]} !important;
  --sidebar-background-color: #${C[bg]} !important;
  --sidebar-text-color: #${C[fg]} !important;
  --lwt-accent-color: #${C[bg]} !important;
  --lwt-text-color: #${C[fg]} !important;
}
EOF

# Import in userChrome.css if not already
if [[ -f "$CHROME_DIR/userChrome.css" ]]; then
  grep -q "userChrome-theme.css" "$CHROME_DIR/userChrome.css" || \
    echo '@import "userChrome-theme.css";' >> "$CHROME_DIR/userChrome.css"
else
  echo '@import "userChrome-theme.css";' > "$CHROME_DIR/userChrome.css"
fi

echo -e "    ${GREEN}zen browser${RESET}"
