# GTK4 / libadwaita theme sync (Nautilus, Loupe, etc.)

mkdir -p "$HOME/.config/gtk-4.0"

cat > "$HOME/.config/gtk-4.0/gtk.css" << EOF
/* Auto-generated by theme sync */
@define-color accent_bg_color #${C[accent]:-${C[blue]}};
@define-color accent_fg_color #${C[bg]};
@define-color accent_color #${C[accent]:-${C[blue]}};
@define-color window_bg_color #${C[bg]};
@define-color window_fg_color #${C[fg]};
@define-color view_bg_color #${C[bg_light]};
@define-color view_fg_color #${C[fg]};
@define-color headerbar_bg_color #${C[bg]};
@define-color headerbar_fg_color #${C[fg]};
@define-color headerbar_border_color #${C[border]};
@define-color card_bg_color #${C[bg_light]};
@define-color card_fg_color #${C[fg]};
@define-color popover_bg_color #${C[bg_light]};
@define-color popover_fg_color #${C[fg]};
@define-color sidebar_bg_color #${C[bg]};
@define-color sidebar_fg_color #${C[fg]};
@define-color dialog_bg_color #${C[bg_light]};
@define-color dialog_fg_color #${C[fg]};
@define-color destructive_bg_color #${C[red]};
@define-color destructive_fg_color #${C[bg]};
@define-color success_bg_color #${C[green]};
@define-color success_fg_color #${C[bg]};
@define-color warning_bg_color #${C[yellow]};
@define-color warning_fg_color #${C[bg]};
@define-color error_bg_color #${C[red]};
@define-color error_fg_color #${C[bg]};
EOF

echo -e "    ${GREEN}gtk4/libadwaita${RESET}"
