# GTK3 theme sync — pairs with 15-gtk4.sh for full GTK coverage.
# Uses adw-gtk3 (matches libadwaita visually) as the base theme,
# then overrides palette via ~/.config/gtk-3.0/gtk.css (GTK3 honours
# user @define-color overrides loaded after the theme).

mkdir -p "$HOME/.config/gtk-3.0"

# Pick variant based on palette mode
if $is_light; then
  GTK3_THEME="adw-gtk3"
  PREFER_DARK=0
else
  GTK3_THEME="adw-gtk3-dark"
  PREFER_DARK=1
fi

cat > "$HOME/.config/gtk-3.0/settings.ini" << EOF
[Settings]
gtk-theme-name=${GTK3_THEME}
gtk-icon-theme-name=Papirus-Dark
gtk-cursor-theme-name=Bibata-Modern-Classic
gtk-cursor-theme-size=24
gtk-font-name=${FONT} 11
gtk-application-prefer-dark-theme=${PREFER_DARK}
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
EOF

cat > "$HOME/.config/gtk-3.0/gtk.css" << EOF
/* Auto-generated by theme sync — palette overrides on top of ${GTK3_THEME} */
@define-color theme_bg_color #${C[bg]};
@define-color theme_fg_color #${C[fg]};
@define-color theme_base_color #${C[bg_light]};
@define-color theme_text_color #${C[fg]};
@define-color theme_selected_bg_color #${C[accent]:-${C[blue]}};
@define-color theme_selected_fg_color #${C[bg]};
@define-color theme_unfocused_bg_color #${C[bg]};
@define-color theme_unfocused_fg_color #${C[fg_dim]};
@define-color theme_unfocused_base_color #${C[bg_light]};
@define-color theme_unfocused_text_color #${C[fg_dim]};
@define-color theme_unfocused_selected_bg_color #${C[accent]:-${C[blue]}};
@define-color theme_unfocused_selected_fg_color #${C[bg]};
@define-color insensitive_bg_color #${C[bg]};
@define-color insensitive_fg_color #${C[fg_muted]};
@define-color insensitive_base_color #${C[bg_light]};
@define-color borders #${C[border]};
@define-color unfocused_borders #${C[border]};
@define-color warning_color #${C[yellow]};
@define-color error_color #${C[red]};
@define-color success_color #${C[green]};
EOF

# Notify running GTK3 apps to re-read settings (GtkSettings::notify on theme-name)
gsettings set org.gnome.desktop.interface gtk-theme "${GTK3_THEME}" 2>/dev/null

echo -e "    ${GREEN}gtk3 (${GTK3_THEME})${RESET}"
