# Tmux theme

local TMUX_DIR="$HOME/.config/tmux"
local TMUX_THEME="$TMUX_DIR/theme.conf"

mkdir -p "$TMUX_DIR"

cat > "$TMUX_THEME" << EOF
# Auto-generated by theme sync from ~/.config/theme/palette.conf
# accent = matugen MD3 primary (unified with Quickshell bar / GTK / Hyprland border)

# Force pane backgrounds to inherit terminal bg. Prevents stale @thm_bg from
# matugen tmux templates leaking into live sessions on palette change.
set -g window-style default
set -g window-active-style default

set -g status-style 'bg=#${C[bg_light]} fg=#${C[fg]}'
set -g status-left-style 'bg=#${C[accent]} fg=#${C[bg]} bold'
set -g status-right-style 'bg=#${C[bg_highlight]} fg=#${C[fg_muted]}'
set -g window-status-style 'fg=#${C[fg_muted]}'
set -g window-status-current-style 'bg=#${C[accent]} fg=#${C[bg]} bold'
set -g pane-border-style 'fg=#${C[border]}'
set -g pane-active-border-style 'fg=#${C[accent]}'
set -g message-style 'bg=#${C[accent_secondary]} fg=#${C[bg]} bold'
set -g mode-style 'bg=#${C[bg_highlight]} fg=#${C[fg]}'
EOF

# Hot-reload if tmux is running
if tmux info &>/dev/null; then
  tmux source-file "$TMUX_THEME" 2>/dev/null
fi

echo -e "    ${GREEN}tmux${RESET}"
