# Hyprland colors

local hypr_colors
hypr_colors="# Auto-generated by theme sync from ~/.config/theme/palette.conf
\$background = rgb(${C[bg]})
\$foreground = rgb(${C[fg]})
\$color0 = rgb(${C[black]})
\$color1 = rgb(${C[red]})
\$color2 = rgb(${C[green]})
\$color3 = rgb(${C[yellow]})
\$color4 = rgb(${C[blue]})
\$color5 = rgb(${C[magenta]})
\$color6 = rgb(${C[cyan]})
\$color7 = rgb(${C[white]})
\$color8 = rgb(${C[bright_black]})
\$color9 = rgb(${C[bright_red]})
\$color10 = rgb(${C[bright_green]})
\$color11 = rgb(${C[bright_yellow]})
\$color12 = rgb(${C[bright_blue]})
\$color13 = rgb(${C[bright_magenta]})
\$color14 = rgb(${C[bright_cyan]})
\$color15 = rgb(${C[bright_white]})"
echo "$hypr_colors" > "$HOME/.config/hypr/UserConfigs/monochrome-colors.conf"
echo "$hypr_colors" > "$HOME/.config/hypr/wallust/wallust-hyprland.conf"
echo -e "    ${GREEN}hyprland${RESET}"
